### PR TITLE
Fix: forgot password, reset password style

### PR DESCRIPTION
**Pull request by seanyellowd**
- forgot password
- reset password
- profile page change password modal

https://openware-inc.atlassian.net/browse/BIS-174
 https://www.figma.com/file/o32beobGrHFUk4M7xBjQva/BaseApp---Color-Theme-%2F-Base-Mockups?node-id=13209%3A202239

### CODE REVIEW

**Review by akushniruk — APPROVED** [review]

**Review by dhanuwat — COMMENTED** [review]
Space between input is too big compared to Figma.
For example reset password screen:

Figma:
Screen Shot 2564-09-17 at 14 48 11

Baseapp:
Screen Shot 2564-09-17 at 14 47 24

Please also check the same issue on forgot password screen.

**Comment by seanyellowd** [comment]
Fixed spacing

**Review by dhanuwat — COMMENTED** [review]
A spacing for the first input is too narrow. On some form input a label got overlap to title section.
Screen Shot 2564-09-23 at 15 10 11
Screen Shot 2564-09-23 at 15 11 24

**Comment by seanyellowd** [comment]
Fixed

**Review by dhanuwat — APPROVED** [review]

**Review by akushniruk — APPROVED** [review]

**Pull request merged**
